org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/switchmapper/Yaml2XmlSwitch.java, org.opentosca.yamlconverter.main/src/test/java/org/opentosca/yamlconverter/main/XmlAnyLaxTest.java
#29 A complete example on how to put general mapping to an xml any element.
=> Xmllaxtest

Examples/CSARTemplateYAML/Custom_InstallVM.yml, Examples/CSARTemplateYAML/ns2__WAR.tosca, Examples/CSARTemplateYAML/ns4__UbuntuNodeTypeImplementation.tosca, Examples/CSARTemplateYAML/ns4__UbuntuNodeTypeImplementation_IA_ArtifactTemplate.tosca, Examples/CSARTemplateYAML/ns5__OperatingSystem.tosca, Examples/CSARTemplateYAML/ns5__OperatingSystem.yml, Examples/CSARTemplateYAML/ns5__RootNodeType.tosca, Examples/CSARTemplateYAML/ns5__RootNodeType.yml, Examples/CSARTemplateYAML/ns75__InstallOpenStackVM.tosca, Examples/CSARTemplateYAML/ns75__InstallOpenStackVM.yml, Examples/CSARTemplateYAML/ns75__InstallOpenStackVM_IA.tosca, Examples/CSARTemplateYAML/ns75__InstallOpenStackVM_impl.tosca, Examples/CSARTemplateYAML/ns75__InstallVMServTemplate.tosca, Examples/CSARTemplateYAML/ns75__InstallVMServTemplate.yml
Please merge, so that Michael has access too. We want to work on controlled sources....
=> CSARTemplate yaml files (not tested, not complete)

Examples/CSARTemplateYAML/ns75__InstallVMServTemplate.yml
Corrected some default values.
Changed intendation.
Added constraints.
@msteffl pls check these changes and think of possible solutions for the output section
=> Corrected some default values.

org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/main/Parser.java, org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/main/YamlBeansConverter.java, org.opentosca.yamlconverter.main/src/test/java/org/opentosca/yamlconverter/main/YamlBeansConverterTest.java, org.opentosca.yamlconverter.main/src/test/resources/yaml/inputs.yaml, org.opentosca.yamlconverter.yamlmodel/src/org/opentosca/yamlconverter/yamlmodel/yaml/element/ArtifactType.java, org.opentosca.yamlconverter.yamlmodel/src/org/opentosca/yamlconverter/yamlmodel/yaml/element/Input.java, org.opentosca.yamlconverter.yamlmodel/src/org/opentosca/yamlconverter/yamlmodel/yaml/element/ServiceTemplate.java
- Tests for inputs in yaml files
- Adjusted Input class
- did some fixes (typos mainly)
=> Added tests for inputs and did some fixes

org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/main/Parser.java, org.opentosca.yamlconverter.main/src/test/java/org/opentosca/yamlconverter/main/MasterParserTest.java, org.opentosca.yamlconverter.main/src/test/java/org/opentosca/yamlconverter/main/YamlBeansConverterTest.java, org.opentosca.yamlconverter.main/src/test/resources/yaml/inputs_emptyConstraints.yaml
- added tests for getInputRequirements
- improved getInputRequirements
=> Improved getInputRequirements

Examples/CSARTemplateYAML/CSAR_Template.yml, Examples/CSARTemplateYAML/Custom_InstallVM.yml, Examples/CSARTemplateYAML/TOSCA_definition.yml, Examples/CSARTemplateYAML/ns5__OperatingSystem.yml, Examples/CSARTemplateYAML/ns5__RootNodeType.yml, Examples/CSARTemplateYAML/ns75__InstallOpenStackVM.yml, Examples/InstallVMServTemplate/CSAR_Template.yml, Examples/InstallVMServTemplate/TOSCA_definition.yml
The folder which should be used for the conversion is "InstallVMServTemplate".
=> Final CSARTemplate Version: InstallVMServTemplate

org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/switchmapper/Yaml2XmlSwitch.java, org.opentosca.yamlconverter.main/src/test/java/org/opentosca/yamlconverter/main/MasterParserTest.java, org.opentosca.yamlconverter.main/src/test/java/org/opentosca/yamlconverter/main/YamlBeansConverterTest.java
=> Fixed testdescriptions

org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/main/Parser.java, org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/main/YamlBeansConverter.java, org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/switchmapper/Yaml2XmlSwitch.java, org.opentosca.yamlconverter.main/src/main/resources/yaml/CSAR_Template.yml, org.opentosca.yamlconverter.main/src/main/resources/yaml/inputs_emptyConstraints.yaml, org.opentosca.yamlconverter.yamlmodel/src/org/opentosca/yamlconverter/yamlmodel/yaml/element/ArtifactDefinition.java, org.opentosca.yamlconverter.yamlmodel/src/org/opentosca/yamlconverter/yamlmodel/yaml/element/ArtifactType.java, org.opentosca.yamlconverter.yamlmodel/src/org/opentosca/yamlconverter/yamlmodel/yaml/element/CapabilityDefinition.java, org.opentosca.yamlconverter.yamlmodel/src/org/opentosca/yamlconverter/yamlmodel/yaml/element/CapabilityType.java, org.opentosca.yamlconverter.yamlmodel/src/org/opentosca/yamlconverter/yamlmodel/yaml/element/InterfaceDefinition.java, org.opentosca.yamlconverter.yamlmodel/src/org/opentosca/yamlconverter/yamlmodel/yaml/element/NodeTemplate.java, org.opentosca.yamlconverter.yamlmodel/src/org/opentosca/yamlconverter/yamlmodel/yaml/element/NodeType.java, org.opentosca.yamlconverter.yamlmodel/src/org/opentosca/yamlconverter/yamlmodel/yaml/element/PropertyDefinition.java, org.opentosca.yamlconverter.yamlmodel/src/org/opentosca/yamlconverter/yamlmodel/yaml/element/RelationshipType.java
- added *Definition classes and use them in NodeType and RelationshipType now
- added CSAR_Template.yml to main resources
- updated dependent classes
- adjusted models to use Map<String, Object> instead of Map<String, String>, but just if no *Definition class is applicable
=> Added *Definition classes and adjusted dependent classes

Examples/Moodle/MoodleTypes-Definitions.yml, org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/main/UI/ConsoleUI.java, org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/main/YamlBeansConverter.java, org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/switchmapper/Yaml2XmlSwitch.java, org.opentosca.yamlconverter.main/src/main/resources/yaml/CSAR_Template.yml, org.opentosca.yamlconverter.yamlmodel/src/org/opentosca/yamlconverter/yamlmodel/yaml/element/ArtifactType.java, org.opentosca.yamlconverter.yamlmodel/src/org/opentosca/yamlconverter/yamlmodel/yaml/element/CapabilityType.java, org.opentosca.yamlconverter.yamlmodel/src/org/opentosca/yamlconverter/yamlmodel/yaml/element/NodeType.java, org.opentosca.yamlconverter.yamlmodel/src/org/opentosca/yamlconverter/yamlmodel/yaml/element/RelationshipType.java
needed to adjust interface structure because of an exception 
added processing of artifact types (not complete yet) #74
=> Fixes and support for artifacts, capability types and relationship types

org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/switchmapper/AbstractSubSwitch.java
Fixed problems with advisors regarding Winery upload are fixed so that a CSAR can be uploaded containing the XML and XSD.
=> Fixed XML and XSD generation

org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/main/Parser.java, org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/main/UI/ConsoleUI.java, org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/main/utils/CSARUtil.java, org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/main/utils/FileUtil.java, org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/main/utils/ZipUtils.java
Added automatic building of zipped CSAR to consoleUI. This may help for debugging with the Winery.
=> added csar build step to consoleUI

org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/switchmapper/NodeTemplatesSubSwitch.java, org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/switchmapper/Yaml2XmlSwitch.java, org.opentosca.yamlconverter.main/src/main/resources/yaml/CSAR_Template.yml, org.opentosca.yamlconverter.yamlmodel/src/org/opentosca/yamlconverter/yamlmodel/yaml/element/NodeTemplate.java
I've added methods to process requirements of a NodeTemplate; updated CSAR_Template.yml as well as documentation
This change is related to #95, because the produced CSAR is not accepted to the Winery. Nevertheless, I can't infer to any of these changes from the error.
=> Added methods to process requirements

org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/switchmapper/NodeTemplatesSubSwitch.java, org.opentosca.yamlconverter.main/src/main/resources/yaml/Moodle-Definitions.yml
added setID in createRequirement
eclipse auto formated some stuff...
=> added ID in requirements

org.opentosca.yamlconverter.main/pom.xml, org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/main/JAXBConverter.java, org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/main/NSPrefixMapper.java, org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/main/utils/FileUtil.java, org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/switchmapper/AbstractSubSwitch.java, org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/switchmapper/NodeTemplatesSubSwitch.java, org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/switchmapper/NodeTypesSubSwitch.java, org.opentosca.yamlconverter.main/src/main/resources/yaml/TOSCA_definition.yml, org.opentosca.yamlconverter.yamlmodel/src/org/opentosca/yamlconverter/yamlmodel/yaml/element/NodeType.java
Added maven assembly plugin to create an executable jar file and fixed some bugs which occurred while testing the jar file.
I've removed the usage of the internal NamespacePrefixMapper, because it wasn't working somehow... Now the not-internal NamespacePrefixMapper is used.
=> Executable jar file

org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/main/utils/FileUtil.java, org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/switchmapper/AbstractSubSwitch.java, org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/switchmapper/NodeTemplatesSubSwitch.java, org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/switchmapper/NodeTypesSubSwitch.java, org.opentosca.yamlconverter.main/src/main/resources/yaml/TOSCA_definition.yml, org.opentosca.yamlconverter.yamlmodel/src/org/opentosca/yamlconverter/yamlmodel/yaml/element/NodeType.java
According to #101 requirements are now supported for node types, but only in the short notation!
Also TOSCA definitions file has been added
=> Node type requirements support

org.opentosca.yamlconverter.main/src/main/resources/yaml/nodetemplate.yaml, org.opentosca.yamlconverter.yamlmodel/src/org/opentosca/yamlconverter/yamlmodel/yaml/element/NodeTemplate.java
- also add new example yaml node template file with artifacts and
interfaces
=> #101 simple fix to parse artifacts in node template correctly

org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/main/UI/ConsoleUI.java
=> #118 process exits after a minute of being idle

org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/main/UI/ConsoleUI.java
Removes the time limit, a unused method and a proper fix for #118.
=> #118 process exits if there is no means of handling input

org.opentosca.yamlconverter.main/pom.xml
simple change to have both artifacts same name
=> #114 make both build artifacts same name

Examples/Moodle/Moodle.yml
added missing relation from os to vm
=> Moodle: added missing relation from os to vm

org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/main/utils/ZipUtils.java
added folder creation before filecreation
=> fixed #128

Examples/Websphere_DB2/Websphere_DB2.yml
first, not ready version of webshpere
=> Websphere yaml file

org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/switchmapper/subswitches/NodeTypesSubSwitch.java
property names for artifact properties have been set like <types:tosca.nodes.impl.Bash>...
-> now these names are translated, too
=> fixed translation problem for property names in artifact types

org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/switchmapper/subswitches/NodeTemplatesSubSwitch.java, org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/switchmapper/subswitches/NodeTypesSubSwitch.java, org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/switchmapper/typemapper/AbstractTypeMapper.java, org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/switchmapper/typemapper/BaseTypeMapper.java, org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/switchmapper/typemapper/ElementType.java, org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/switchmapper/typemapper/SpecificTypeMapper.java
The methods for the mapper still needs to be implemented!
=> started implementation for requirement namespace problem

org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/main/interfaces/IToscaYamlParser.java
=> Improved readability of the comments
